server.port=8080
spring.datasource.url=jdbc:sqlite:ecommerce.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Static Resource Handler Configuration
spring.web.resources.static-locations=classpath:/static/,file:public/
spring.mvc.static-path-pattern=/**

